from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Instrumentsdb(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_created = db.Column(db.DateTime, default=db.func.current_timestamp())
    MJD = db.Column(db.Float)
    D01 = db.Column(db.String(255))
    D02 = db.Column(db.Float)
    D03 = db.Column(db.Float)
    D04 = db.Column(db.Float)
    D05 = db.Column(db.Float)
    D06a = db.Column(db.Float)
    D06b = db.Column(db.Float)
    D07 = db.Column(db.String(255))
    D08 = db.Column(db.Float)
    D09 = db.Column(db.Float)
    D10 = db.Column(db.Float)
    D11 = db.Column(db.Float)
    D12 = db.Column(db.Float)
    D13a = db.Column(db.Float)
    D13b = db.Column(db.Float)
    D13c = db.Column(db.Float)
    D13d = db.Column(db.Float)
    D14 = db.Column(db.Float)
    D15a = db.Column(db.Float)
    D15b = db.Column(db.Float)
    D15c = db.Column(db.Float)
    D16 = db.Column(db.Float)
    D17 = db.Column(db.Float)
    D18 = db.Column(db.Float)
    D19 = db.Column(db.Float)
    D20 = db.Column(db.Float)
    D21 = db.Column(db.Float)
